media: media
content:
  - name: pages
    label: Pages
    type: collection
    path: docs
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
  - name: tomls
    label: TOMLS
    type: collection
    path: docs/tomls
    fields:
      - name: title
        type: string
      - name: body
        type: toml